/**
 * Resolves a tenant slug from a request's host header (or URL path fallback).
 *
 * Rules:
 *   - Subdomain wins: `mm.operatehq.app` → "mm"
 *   - `*.localhost` dev convenience: `mm.localhost:3000` → "mm"
 *   - Reserved slugs (configured by env): "admin", "book", "www", "api" return null
 *   - Apex domain returns null (caller decides: marketing? booking funnel?)
 *
 * The PATH fallback (`/t/{slug}/...`) is resolved separately by middleware
 * and rewritten into a subdomain-style header so downstream code only
 * deals with one resolution model.
 */

export type TenantSource = "subdomain" | "path" | null;

export interface ResolvedTenant {
  slug: string | null;
  source: TenantSource;
  /** If non-null, the request matched a reserved name (e.g. "admin"). */
  reserved: string | null;
}

const RESERVED_SUBDOMAINS = new Set([
  "www",
  "api",
  "admin", // super-admin console
  "book",  // public Track B booking funnel
  "app",
  "auth",
]);

export interface ResolveOptions {
  apexDomain?: string;
  reserved?: ReadonlySet<string>;
}

// Hostnames whose subdomains are NEVER tenants — generated by hosting
// providers + always treated as apex. Add to this if you add another
// platform.
const APEX_ONLY_SUFFIXES = [
  ".run.app",     // Cloud Run (e.g. operate-web-123.us-central1.run.app)
  ".a.run.app",   // Cloud Run alt format
  ".cloudfunctions.net",
  ".appspot.com",
  ".vercel.app",
  ".netlify.app",
  ".fly.dev",
];

export function resolveTenantFromHost(
  host: string | null | undefined,
  options: ResolveOptions = {},
): ResolvedTenant {
  if (!host) return { slug: null, source: null, reserved: null };

  const reserved = options.reserved ?? RESERVED_SUBDOMAINS;
  const hostname = host.split(":")[0]?.toLowerCase() ?? "";

  // Hosting-provider hostnames are always apex — never decode tenant from them
  for (const suffix of APEX_ONLY_SUFFIXES) {
    if (hostname.endsWith(suffix)) {
      return { slug: null, source: null, reserved: null };
    }
  }

  // If an explicit APP_DOMAIN is set, only treat the host as a tenant URL
  // when it's exactly `{slug}.{APP_DOMAIN}`. Other hosts are apex.
  const apex = options.apexDomain ?? process.env.APP_DOMAIN;
  if (apex && apex !== "localhost") {
    if (hostname === apex) {
      return { slug: null, source: null, reserved: null };
    }
    if (!hostname.endsWith("." + apex)) {
      return { slug: null, source: null, reserved: null };
    }
  }

  const parts = hostname.split(".").filter(Boolean);
  if (parts.length < 2) return { slug: null, source: null, reserved: null };

  const first = parts[0];
  if (!first) return { slug: null, source: null, reserved: null };

  if (reserved.has(first)) {
    return { slug: null, source: null, reserved: first };
  }

  // *.localhost dev convenience (browsers route *.localhost → 127.0.0.1)
  if (parts.length === 2 && parts[1] === "localhost") {
    return { slug: first, source: "subdomain", reserved: null };
  }

  // Apex (2-part TLD like operatehq.app) → no tenant
  if (parts.length === 2) {
    return { slug: null, source: null, reserved: null };
  }

  // 3+ parts → first segment is the tenant
  return { slug: first, source: "subdomain", reserved: null };
}

/**
 * Resolves a tenant slug from a URL pathname (path-fallback mode).
 * Matches `/t/{slug}` or `/t/{slug}/...` and returns the slug; otherwise null.
 */
export function resolveTenantFromPath(
  pathname: string | null | undefined,
): string | null {
  if (!pathname) return null;
  const match = /^\/t\/([a-z0-9][a-z0-9-]*)(?:\/|$)/.exec(pathname);
  return match?.[1] ?? null;
}

/**
 * Resolves a tenant slug from a vanity domain map (string env var).
 *
 * `mapEnv` is formatted as `domain1=slug1,domain2=slug2`. Pure string
 * logic so it's safe to call from Edge middleware.
 *
 * Used twice in middleware:
 *   - PUBLIC_SITE_DOMAIN_MAP → apex domain → /sites/{slug} (marketing)
 *   - APP_DOMAIN_MAP         → ops subdomain → /t/{slug}   (internal)
 *
 * The DB columns on `Tenant.customDomain` (public) and `Tenant.appDomain`
 * (internal) are the source of truth; the env vars are the runtime knobs.
 *
 * Whitespace around entries is ignored. Empty / malformed entries are skipped.
 */
export function resolveSlugFromDomainMap(
  host: string | null | undefined,
  mapEnv: string | null | undefined,
): string | null {
  if (!host || !mapEnv) return null;
  const hostname = host.split(":")[0]?.toLowerCase();
  if (!hostname) return null;

  for (const entry of mapEnv.split(",")) {
    const trimmed = entry.trim();
    if (!trimmed) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0 || eq === trimmed.length - 1) continue;
    const domain = trimmed.slice(0, eq).trim().toLowerCase();
    const slug = trimmed.slice(eq + 1).trim();
    if (!domain || !slug) continue;
    if (domain === hostname) return slug;
  }
  return null;
}

/** @deprecated Use resolveSlugFromDomainMap. Kept for one release for callers. */
export const resolveTenantFromCustomDomain = resolveSlugFromDomainMap;
